# https://travis-ci.org/tornadoweb/tornado
language: python
python:
    - 3.6

install:
    - pip install -r requirements/lint.txt

script:
    - pylint task_tracker

sudo: false

matrix:
    fast_finish: true
