# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 19:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата зачисления')),
                ('points', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Количество зачистенных очков')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('estimate', models.DateField(verbose_name='Срок выполнения')),
                ('state', models.CharField(choices=[('INP', 'in_progress'), ('RDY', 'ready')], default='INP', max_length=3, verbose_name='Статус выполнения')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('roadmap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Roadmap', verbose_name='Дорожная карта')),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task', verbose_name='Задача'),
        ),
    ]
