# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20170518_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата зачисления')),
                ('points', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Количество зачистенных очков')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scores',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task', verbose_name='Задача'),
        ),
    ]
