# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20170518_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
