# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20170520_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='tasks.Task', verbose_name='Задача'),
        ),
    ]
